import React, { useRef } from 'react'
import { Modal } from './Modal'
import { Button } from './Button'
import { Badge } from './Badge'
import { Award, Printer, Download, CheckCircle, Shield, Zap } from 'lucide-react'
import { formatDate } from '../../lib/utils'

export function CertificateModal({
  isOpen,
  onClose,
  userName = 'Speed Typist',
  wpm = 85,
  accuracy = 98.5,
  testDate = new Date().toISOString()
}) {
  const certificateRef = useRef(null)

  const handlePrint = () => {
    window.print()
  }

  // Determine achievement title based on WPM
  const getRankTitle = (speed) => {
    if (speed >= 100) return 'Velocity Grandmaster'
    if (speed >= 80) return 'Keyboard Specialist'
    if (speed >= 60) return 'Fluid Touch Typist'
    if (speed >= 40) return 'Proficient Typist'
    return 'Typing Fundamentals'
  }

  const certificateId = `TF-${Math.abs(Math.sin(wpm) * 1000000).toFixed(0).padStart(6, '0')}-${new Date(testDate).getFullYear()}`

  return (
    <Modal isOpen={isOpen} onClose={onClose} maxWidth="max-w-2xl" showClose={true}>
      <div className="space-y-6">
        {/* Certificate Display Area (Printable) */}
        <div
          ref={certificateRef}
          className="relative p-8 sm:p-10 rounded-3xl border-4 border-double border-amber-500/50 bg-gradient-to-b from-amber-500/5 via-white to-amber-500/10 dark:from-slate-900 dark:via-slate-950 dark:to-slate-900 shadow-2xl text-center overflow-hidden"
        >
          {/* Subtle watermark background icon */}
          <Zap className="w-96 h-96 absolute -top-20 -right-20 text-brand-500/5 pointer-events-none" />

          {/* Header */}
          <div className="flex items-center justify-center gap-2 mb-2">
            <div className="w-8 h-8 rounded-xl bg-amber-500 text-white flex items-center justify-center font-black">
              <Award className="w-5 h-5 fill-current" />
            </div>
            <span className="text-sm font-black tracking-widest uppercase text-amber-600 dark:text-amber-400">
              TypSmart OFFICIAL VERIFICATION
            </span>
          </div>

          <h2 className="text-2xl sm:text-4xl font-black text-slate-900 dark:text-white tracking-tight uppercase mt-2">
            Certificate of Achievement
          </h2>

          <p className="text-xs text-slate-400 uppercase tracking-widest mt-1">
            This verification acknowledges that
          </p>

          {/* Recipient Name */}
          <div className="my-6 py-2 border-b-2 border-slate-300 dark:border-slate-700 max-w-md mx-auto">
            <span className="text-2xl sm:text-3xl font-extrabold text-brand-600 dark:text-brand-400 font-sans">
              {userName}
            </span>
          </div>

          <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 max-w-lg mx-auto leading-relaxed">
            has demonstrated verified keyboard speed and precision on the TypSmart standardized testing engine, earning the distinction of:
          </p>

          <div className="mt-4 mb-6">
            <span className="px-4 py-2 rounded-2xl bg-amber-500/10 border border-amber-500/30 text-amber-700 dark:text-amber-300 font-extrabold text-lg sm:text-xl">
              {getRankTitle(wpm)}
            </span>
          </div>

          {/* Verified Stats Row */}
          <div className="grid grid-cols-2 gap-4 max-w-xs mx-auto p-3 rounded-2xl bg-white/80 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 mb-6">
            <div>
              <p className="text-[10px] uppercase font-bold text-slate-400">Tested Speed</p>
              <p className="text-2xl font-black font-mono text-brand-600 dark:text-brand-400">{wpm} WPM</p>
            </div>
            <div>
              <p className="text-[10px] uppercase font-bold text-slate-400">Accuracy</p>
              <p className="text-2xl font-black font-mono text-emerald-600 dark:text-emerald-400">{accuracy}%</p>
            </div>
          </div>

          {/* Footer of certificate */}
          <div className="pt-4 border-t border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-400 gap-2">
            <div>
              <span>Date: <strong>{formatDate(testDate)}</strong></span>
            </div>
            <div className="font-mono text-[11px]">
              <span>ID: <strong>{certificateId}</strong></span>
            </div>
          </div>
        </div>

        {/* Disclaimer as required by master prompt */}
        <p className="text-[11px] text-slate-400 text-center leading-relaxed">
          * Notice: This milestone certificate is generated by TypSmart for personal skill verification and practice benchmarking. It is not an accredited academic diploma or state-certified credential.
        </p>

        {/* Action Buttons */}
        <div className="flex items-center justify-end gap-3 pt-2">
          <Button variant="ghost" onClick={onClose}>
            Close
          </Button>
          <Button variant="primary" onClick={handlePrint} icon={Printer}>
            Print / Save as PDF
          </Button>
        </div>
      </div>
    </Modal>
  )
}
